language: go
install:
  - go get github.com/kr/pretty
  - go get github.com/bmizerany/assert
  - go get golang.org/x/net/websocket
  - go get github.com/golang/protobuf/proto
script:
    - pushd $TRAVIS_BUILD_DIR
    - ./all.sh
    - popd
notifications:
  email: false
