#!/bin/sh

set -e

exec 2>&1

n=$1 ; [ -z $n ] && n=1

expr "$(uname)" : "Darwin" && {
    sudo ifconfig lo0 add 127.0.0.$n
}

if [ $n = "1" ]
then juntad                   -l 127.0.0.1:8046  -w 127.0.0.1:8080
else juntad -a 127.0.0.1:8046 -l 127.0.0.$n:8046 -w 127.0.0.$n:8080
fi
