#!/bin/bash

set -e

n=$1
[ -z "$n" ] && n=3

which seq  && seq=seq
which gseq && seq=gseq

if [ -z "$seq" ]
then
    printf 'Could not find `seq` or `gseq`\n'
    exit 1
fi

waitall() {
    while test $running -ge 1
    do
        wait
        running=$(expr $running - 1)
    done
}

quit() {
    killall doozerd
    waitall
}

trap quit INT

running=0
for i in $($seq $n)
do
    (uname | grep -q Darwin) && {
        sudo ifconfig lo0 add 127.0.0.$i
    }

    ./fr $i &
    running=$(expr $running + 1)

    sleep 1
done

waitall
