include $(GOROOT)/src/Make.$(GOARCH)

TARG=junta/paxos
GOFILES=\
	paxos.go\
	cluster.go\
	putter.go\
	manager.go\
	instance.go\
	keys.go\
	coordinator.go\
	acceptor.go\
	learner.go\
	message.go\
	registrar.go\
	sink.go\

include $(GOROOT)/src/Make.pkg
