// Code generated by protoc-gen-go from "m.proto"
// DO NOT EDIT!

package consensus

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type msg_Cmd int32

const (
	msg_NOP      = 0
	msg_INVITE   = 1
	msg_RSVP     = 2
	msg_NOMINATE = 3
	msg_VOTE     = 4
	msg_TICK     = 5
	msg_PROPOSE  = 6
	msg_LEARN    = 7
)

var msg_Cmd_name = map[int32]string{
	0: "NOP",
	1: "INVITE",
	2: "RSVP",
	3: "NOMINATE",
	4: "VOTE",
	5: "TICK",
	6: "PROPOSE",
	7: "LEARN",
}
var msg_Cmd_value = map[string]int32{
	"NOP":      0,
	"INVITE":   1,
	"RSVP":     2,
	"NOMINATE": 3,
	"VOTE":     4,
	"TICK":     5,
	"PROPOSE":  6,
	"LEARN":    7,
}

func newMsg_Cmd(x int32) *msg_Cmd {
	e := msg_Cmd(x)
	return &e
}

type msg struct {
	Cmd              *msg_Cmd "PB(varint,1,opt,name=cmd,enum=consensus.msg_Cmd)"
	Seqn             *int64   "PB(varint,2,opt,name=seqn)"
	Crnd             *int64   "PB(varint,3,opt,name=crnd)"
	Vrnd             *int64   "PB(varint,4,opt,name=vrnd)"
	Value            []byte   "PB(bytes,5,opt,name=value)"
	XXX_unrecognized []byte
}

func (this *msg) Reset() {
	*this = msg{}
}

func init() {
	proto.RegisterEnum("consensus.msg_Cmd", msg_Cmd_name, msg_Cmd_value)
}
