// Code generated by protoc-gen-go from "m.proto"
// DO NOT EDIT!

package consensus

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type M_Cmd int32

const (
	M_NOP      = 0
	M_INVITE   = 1
	M_RSVP     = 2
	M_NOMINATE = 3
	M_VOTE     = 4
	M_TICK     = 5
	M_PROPOSE  = 6
	M_LEARN    = 7
)

var M_Cmd_name = map[int32]string{
	0: "NOP",
	1: "INVITE",
	2: "RSVP",
	3: "NOMINATE",
	4: "VOTE",
	5: "TICK",
	6: "PROPOSE",
	7: "LEARN",
}
var M_Cmd_value = map[string]int32{
	"NOP":      0,
	"INVITE":   1,
	"RSVP":     2,
	"NOMINATE": 3,
	"VOTE":     4,
	"TICK":     5,
	"PROPOSE":  6,
	"LEARN":    7,
}

func NewM_Cmd(x int32) *M_Cmd {
	e := M_Cmd(x)
	return &e
}

type M struct {
	Cmd              *M_Cmd "PB(varint,1,opt,name=cmd,enum=consensus.M_Cmd)"
	Seqn             *int64 "PB(varint,2,opt,name=seqn)"
	Crnd             *int64 "PB(varint,3,opt,name=crnd)"
	Vrnd             *int64 "PB(varint,4,opt,name=vrnd)"
	Value            []byte "PB(bytes,5,opt,name=value)"
	XXX_unrecognized []byte
}

func (this *M) Reset() {
	*this = M{}
}

func init() {
	proto.RegisterEnum("consensus.M_Cmd", M_Cmd_name, M_Cmd_value)
}
