include ../../Make.inc

TARG=doozer/consensus
GOFILES=\
	run.go\
	learner.go\
	m.go\
	m.pb.go\
	sink.go\

include $(GOROOT)/src/Make.pkg
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf
