include ../../Make.inc

TARG=doozer/consensus
GOFILES=\
	consensus.go\
	run.go\
	coordinator.go\
	acceptor.go\
	learner.go\
	m.go\
	m.pb.go\
	manager.go\

include $(GOROOT)/src/Make.pkg
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf
