#!/usr/bin/env ruby
session_name = ARGV[0] || 'doozer'


def _system(*args)
  system(*args)
end

master_id = "88fca87ce04b0276"

__DIR__ = File.expand_path(File.dirname(__FILE__))

  argv = [
    "-S", session_name,
    "-X",
    [
      "screen",
      "-t", "doozerdM",
      "#{__DIR__}/doozerd",
      "-i", master_id,
      "-l", ":8040"
    ],
  ].flatten

  _system("screen", *argv)

(8041..8044).each do |port|
  argv = [
    "-S", session_name,
    "-X",
    [
      "screen",
      "-t", "doozerd#{port}",
      "#{__DIR__}/doozerd",
      "-a", master_id+"=:8040",
      "-l", ":#{port}"
    ]
  ].flatten

  _system("screen", *argv)
end
