include ../../Make.inc

TARG=doozer/paxos
GOFILES=\
	paxos.go\
	cluster.go\
	coding.go\
	putter.go\
	manager.go\
	instance.go\
	keys.go\
	coordinator.go\
	acceptor.go\
	learner.go\
	msg.pb.go\
	message.go\
	registrar.go\
	sink.go\

include $(GOROOT)/src/Make.pkg
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf
