#!/bin/sh

encstr() {
  printf '$%d\r\n%s\r\n' ${#1} "$1"
}

encstrs() {
  printf '*%d\r\n' $#
  for x in "$@"
  do
    encstr "$x"
  done
}

jdel() {
  encstrs del "$@"
}

jdel "$@" | nc localhost 8046
